name: Generar Galería JSON

# Permisos para permitir que GitHub Actions haga push
permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout del repo con token para push
    - name: Chequear repo
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    # 2️⃣ Configurar Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # 3️⃣ Generar galeria.json
    - name: Generar galeria.json
      run: |
        node <<'EOF'
        const fs = require('fs');
        const path = require('path');

        const imgDir = path.join(process.cwd(), 'assets/img');
        const outputFile = path.join(process.cwd(), 'galeria.json');

        function walkDir(dir) {
          const files = fs.readdirSync(dir, { withFileTypes: true });
          let results = [];
          for (const file of files) {
            const fullPath = path.join(dir, file.name);
            if (file.isDirectory()) {
              results = results.concat(walkDir(fullPath));
            } else if (/\.(png|jpg|jpeg|gif)$/i.test(file.name)) {
              const relativePath = path.relative(process.cwd(), fullPath).replace(/\\/g,'/');
              const parts = relativePath.split('/');

              const year = parseInt(parts[2]);
              const tags = parts.slice(3, -1); // toma todas las carpetas después del año, antes del archivo

              results.push({
                year,
                tags,
                url: relativePath
              });
            }
          }
          return results;
        }

        const images = walkDir(imgDir);
        fs.writeFileSync(outputFile, JSON.stringify(images, null, 2));
        console.log(`galeria.json generado con ${images.length} imágenes`);

        EOF


    # 4️⃣ Commit y push automático usando GITHUB_TOKEN
    - name: Commit y push
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add galeria.json
        git commit -m "Actualizar galeria.json [Automático]" || echo "No hay cambios"
        git push
